### ISSUE TITLE
Documentation checklist for 2019.11

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3104]
#  Additions:
 * [ ] [6.e] `LEXICAL::` pseudo-package includes all symbols visible in
        the lexical scope, including dynamic symbols from caller
        chain -[56af07bf](https://github.com/rakudo/rakudo/commit/56af07bf)
 * [ ] [6.e] `SETTING::` pseudo-package includes all symbols from all
        available `CORE`s -[56af07bf](https://github.com/rakudo/rakudo/commit/56af07bf)
 * [ ] [6.e] `UNIT::` pseudo-package includes all lexicals visible at
        unit level -[56af07bf](https://github.com/rakudo/rakudo/commit/56af07bf)
 * [ ] [6.e] Symbol binding is now possible for all
        pseudo-packages -[56af07bf](https://github.com/rakudo/rakudo/commit/56af07bf)
 * [ ] Individual language-release `CORE`s are now accessible
        via `CORE::v6<rev>` namespaces. -[6a885908](https://github.com/rakudo/rakudo/commit/6a885908)
 * [ ] Added GB2312 and GB18030 encodings -[a95cb03b](https://github.com/rakudo/rakudo/commit/a95cb03b)-[4cee2c36](https://github.com/rakudo/rakudo/commit/4cee2c36)
 * [ ] Added support for Unicode v12.1 -[f5ef0b3c](https://github.com/rakudo/rakudo/commit/f5ef0b3c)-[7056a25a](https://github.com/rakudo/rakudo/commit/7056a25a) 
#  Build system:
 * [ ] Added `raku` and `rakudo` executables -[5090206d](https://github.com/rakudo/rakudo/commit/5090206d)-[ab0a6d61](https://github.com/rakudo/rakudo/commit/ab0a6d61)
 * [ ] Added `--rakudo-home` alias to `--perl6-home` -[dfeb7126](https://github.com/rakudo/rakudo/commit/dfeb7126)
 * [ ] Added `--nqp-home` and `--perl6-home` configure options to set
        custom home dirs -[e16e61a8](https://github.com/rakudo/rakudo/commit/e16e61a8)
 * [ ] Added `RAKUDO_HOME` environment variable -[dfeb7126](https://github.com/rakudo/rakudo/commit/dfeb7126)-[24abab8a](https://github.com/rakudo/rakudo/commit/24abab8a)
 * [ ] Added support for `.rakumod` extension -[daa16b9c](https://github.com/rakudo/rakudo/commit/daa16b9c)
 * [ ] Added `--silent-build` option -[f9ee6043](https://github.com/rakudo/rakudo/commit/f9ee6043)
 * [ ] Fixed errors when building from a release archive -[78c05c12](https://github.com/rakudo/rakudo/commit/78c05c12)
 * [ ] Fixed installation to `/usr` -[1e0220ff](https://github.com/rakudo/rakudo/commit/1e0220ff)
 * [ ] Fixed build in folders with spaces -[93669907](https://github.com/rakudo/rakudo/commit/93669907)-[abc072cd](https://github.com/rakudo/rakudo/commit/abc072cd)-[f1170895](https://github.com/rakudo/rakudo/commit/f1170895)
        -[0365662e](https://github.com/rakudo/rakudo/commit/0365662e)-[f7f9b1fc](https://github.com/rakudo/rakudo/commit/f7f9b1fc)-[ceb457e1](https://github.com/rakudo/rakudo/commit/ceb457e1)-[12d9e34a](https://github.com/rakudo/rakudo/commit/12d9e34a)
 * [ ] Created a process for making binary releases -[34273916](https://github.com/rakudo/rakudo/commit/34273916)
        -[1c764404](https://github.com/rakudo/rakudo/commit/1c764404)-[f7b4d71f](https://github.com/rakudo/rakudo/commit/f7b4d71f)
 * [ ] Fixed libffi include issue -[98e0bb68](https://github.com/rakudo/rakudo/commit/98e0bb68)
 * [ ] Removed `--libdir` configure option -[cdd57cd0](https://github.com/rakudo/rakudo/commit/cdd57cd0)
 * [ ] Fixed the build to not create folders outside the build
        directory -[cbd1dc27](https://github.com/rakudo/rakudo/commit/cbd1dc27)
 * [ ] Minor build system fixes -[165f3fbf](https://github.com/rakudo/rakudo/commit/165f3fbf)-[3d5c5517](https://github.com/rakudo/rakudo/commit/3d5c5517)-[579ac66e](https://github.com/rakudo/rakudo/commit/579ac66e)
        -[d487cd85](https://github.com/rakudo/rakudo/commit/d487cd85)-[c2808b32](https://github.com/rakudo/rakudo/commit/c2808b32)-[cfb0a267](https://github.com/rakudo/rakudo/commit/cfb0a267)
 * [ ] General build system cleanup -[90de22f8](https://github.com/rakudo/rakudo/commit/90de22f8)-[983c3985](https://github.com/rakudo/rakudo/commit/983c3985)-[4ce5b7c5](https://github.com/rakudo/rakudo/commit/4ce5b7c5)
        -[ff9272b1](https://github.com/rakudo/rakudo/commit/ff9272b1)-[608c6cdc](https://github.com/rakudo/rakudo/commit/608c6cdc)-[9fefa336](https://github.com/rakudo/rakudo/commit/9fefa336)

**Comment by coke** [comment]
Most of the build system items are probably not relevant for these docs.
