### ISSUE TITLE
Checklist for 2020.07

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3527]
Here are the additions in the [new release](https://github.com/rakudo/rakudo/blob/master/docs/announce/2020.07.md)

#  Additions:
 * [x] Set equality operators: `(==)` Unicode `≡` and `≢` which allow to check
      for sameness of the operands using QuantHash semantics
      (for example, `1,2,3 (==) 3,1,2` returns `True`) -[701f4cfb](https://github.com/rakudo/rakudo/commit/701f4cfb)-[dbd69ba7](https://github.com/rakudo/rakudo/commit/dbd69ba7)
 * [x] Add support for Supply.tail(*) and .tail(Inf) -[9ccfc90e](https://github.com/rakudo/rakudo/commit/9ccfc90e)
 * [x] Add support for Supply.tail(*-3) -[eaa72afa](https://github.com/rakudo/rakudo/commit/eaa72afa)
 * [x] Make `Supply.head(*-3)` consistent with `List.head(*-3)` -[5c8c7324](https://github.com/rakudo/rakudo/commit/5c8c7324)-[70e5cfb9](https://github.com/rakudo/rakudo/commit/70e5cfb9)
 * [x] Rakudo now supports the `--rakudo-home` command line option to specify the path of the Rakudo home -[914bcbad](https://github.com/rakudo/rakudo/commit/914bcbad)

**Comment by lizmat** [comment]
Not sure if / where Rakudo command line parameters are documented?

**Comment by coke** [comment]
rakudo-home was already listed when I checked (last unchecked item, lizmat++)
