### ISSUE TITLE
Checklist for 2020.08

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3580]
#  Changes:
 * [x] Methods `name` and `usage-name` of `Parameter` now return an empty `Str`,
      when there is no name, instead of `Nil`. Method `default` returns `Code` type object,
      when no default was provided instead of `Any` type object -[c11f4b18](https://github.com/rakudo/rakudo/commit/c11f4b18)
 * [x] Remove redundant `(())` from `Map.new.raku` -[491e1def](https://github.com/rakudo/rakudo/commit/491e1def)
 * [x] Routine `done-testing` of `Test` module returns `Bool` now,
      indicating if the tests passed or not -[337848fe](https://github.com/rakudo/rakudo/commit/337848fe) 

#  Additions:
 * [ ] Add `set_parameterizer`, `parameterize_type`, `type_parameterized`,
      `type_parameters` and `type_parameter_at` methods for `Metamodel::Primitives` -[2ab94429](https://github.com/rakudo/rakudo/commit/2ab94429)

**Comment by coke** [comment]
the .raku output format isn't fully doc'd, we don't need to put this update in.

**Comment by coke** [comment]
None of the metamodel primitive items are spec'd in roast. Closing ticket.
