### ISSUE TITLE
Checklist for 2021.03

### ISSUE THREAD

**Issue by JJ** [Raku/doc#3828]
Changes mentioned [in the latest release](https://github.com/rakudo/rakudo/blob/master/docs/announce/2021.03.md)

#  Additions:
 * [x] Implement space-delimited command line interface arguments -[54b6ff30](https://github.com/rakudo/rakudo/commit/54b6ff30)-[244abf6e](https://github.com/rakudo/rakudo/commit/244abf6e)-[67143a6d](https://github.com/rakudo/rakudo/commit/67143a6d)
 * [x] Add a predicated wait for `Lock::ConditionVariable` -[b4980a1c](https://github.com/rakudo/rakudo/commit/b4980a1c)-[30e07901](https://github.com/rakudo/rakudo/commit/30e07901)-[94c562c4](https://github.com/rakudo/rakudo/commit/94c562c4)
 * [x] The `Pod::To::Text` module's output supports rendering of multi-level lists now -[76dab72f](https://github.com/rakudo/rakudo/commit/76dab72f)

**Comment by Altai-man** [comment]
I think the list is copied from some other release?

**Comment by JJ** [comment]
Is it? Let me check...

**Comment by JJ** [comment]
Right...

**Comment by JJ** [comment]
First one fixed at e01b3c416f7d8234231121e99fb36091a3d25b67 (forgot to reference the issue)

**Comment by coke** [comment]
The pod docs already mention multi-level lists, with no caveats about their formatting, so considering the 3rd item done
