### ISSUE TITLE
Checklist for 2021.12

### ISSUE THREAD

**Issue by JJ** [Raku/doc#4002]
[Original announcement](https://github.com/rakudo/rakudo/blob/master/docs/announce/2021.12.md)

#  Additions:
 * [x] Add is-wrapped method to Routine (#4579) -[99bc766e](https://github.com/rakudo/rakudo/commit/99bc766e)
 * [x] Introducing RAKUDO_PRECOMPILATION_PROGRESS -[d88d1cc0](https://github.com/rakudo/rakudo/commit/d88d1cc0)
 * [x] Add a IterationBuffer.new(iterable) candidate (#4599) -[ad145b4c](https://github.com/rakudo/rakudo/commit/ad145b4c)
 * [x] Add IterationBuffer.unshift/prepend methods (#4641) -[259d29b3](https://github.com/rakudo/rakudo/commit/259d29b3)
 * [x] Add knowledge about MacOS Monterey -[1fc8cce3](https://github.com/rakudo/rakudo/commit/1fc8cce3)
 * [x] Add the ability to display any default values in sub MAIN to the default
      USAGE message -[0b286ed2](https://github.com/rakudo/rakudo/commit/0b286ed2) 
#  Changes:
 * [x] Remove redundant multi method list(QuantHash:U:) -[8fd65670](https://github.com/rakudo/rakudo/commit/8fd65670)
 * [x] Very simple ACCEPTS for Int:D vs Int:D (#4625) -[57387455](https://github.com/rakudo/rakudo/commit/57387455)
 * [x] Get either parametric or concrete roles in MRO when requested -[641a86d5](https://github.com/rakudo/rakudo/commit/641a86d5)
      -[832a8476](https://github.com/rakudo/rakudo/commit/832a8476)-[bf2a07fb](https://github.com/rakudo/rakudo/commit/bf2a07fb)-[856f1af0](https://github.com/rakudo/rakudo/commit/856f1af0)
 * [x] Remove support for use experimental :collation (#4616) -[eb837dee](https://github.com/rakudo/rakudo/commit/eb837dee)
 * [x] Make Telemetry::snap(:head) return the filename -[ad1fddbb](https://github.com/rakudo/rakudo/commit/ad1fddbb)
 * [x] Make the max number of threads depend on number of cores (#4652)
      -[afc56429](https://github.com/rakudo/rakudo/commit/afc56429)

**Comment by coke** [comment]
Everything is now checked (lizmat++), closing.
