### ISSUE TITLE
Checklist for 2022.02

### ISSUE THREAD

**Issue by JJ** [Raku/doc#4034]
[Original announcement](https://github.com/rakudo/rakudo/blob/master/docs/announce/2022.02.md)

#  Additions:
 * [x] Add support for $RAKUDO_OPT environment variable -[e82e6774](https://github.com/rakudo/rakudo/commit/e82e6774)
 * [x] Implement sub rotor -[90a04ac0](https://github.com/rakudo/rakudo/commit/90a04ac0)
 * [x] Introducing $*RAT-OVERFLOW (#4299) -[f737b080](https://github.com/rakudo/rakudo/commit/f737b080)
 * [x] Add Cool.Order "coercer" (#4473) -[4b2fc66f](https://github.com/rakudo/rakudo/commit/4b2fc66f)
 * [x] Add CI job that runs a spectest instead of Rakudo tests -[7ef7b6ed](https://github.com/rakudo/rakudo/commit/7ef7b6ed)
 * [x] Add :slip named argument to roundrobin() -[de605e84](https://github.com/rakudo/rakudo/commit/de605e84)
 * [x] Add an Any(iterable).infer method (#4626) -[4d263779](https://github.com/rakudo/rakudo/commit/4d263779)
 * [x] Add ACCEPTS candidate for Junction to Bool -[f21af28e](https://github.com/rakudo/rakudo/commit/f21af28e)
 * [x] Add missing checks for nulls -[821195b2](https://github.com/rakudo/rakudo/commit/821195b2)
 * [x] Add missing precedence info for some infix ops (#4725) -[cd86606e](https://github.com/rakudo/rakudo/commit/cd86606e)
 * [x] Add .unique to native arrays -[bc8c286f](https://github.com/rakudo/rakudo/commit/bc8c286f)
 * [x] Add .repeated to native arrays -[369093c8](https://github.com/rakudo/rakudo/commit/369093c8)
 * [x] Add .squish to native arrays -[284b5623](https://github.com/rakudo/rakudo/commit/284b5623)

#  Removals:
 * [x] Remove uniprop-(int|str|bool) -[cc5f17a0](https://github.com/rakudo/rakudo/commit/cc5f17a0) -[2b355dc4](https://github.com/rakudo/rakudo/commit/2b355dc4)
 * [x] Remove check for nullness of descriptor -[b2f0a9d2](https://github.com/rakudo/rakudo/commit/b2f0a9d2)
 * [x] Remove some no longer needed CALL-MEs -[25ca2064](https://github.com/rakudo/rakudo/commit/25ca2064)
 * [x] Remove RESTRICTED setting (#3965) -[6a8fa2f4](https://github.com/rakudo/rakudo/commit/6a8fa2f4)
 * [x] Remove two dummy parameters from (Fat)Rat coercer -[6c765609](https://github.com/rakudo/rakudo/commit/6c765609)

**Comment by lizmat** [comment]
Yeah, more generally, the changelog will need a little more massaging / summarizing in the next release.

**Comment by coke** [comment]
Everything is now checked (lizmat++), closing
