### ISSUE TITLE
Checklist for 2022.03

### ISSUE THREAD

**Issue by JJ** [Raku/doc#4043]
[Original announcement](https://github.com/rakudo/rakudo/blob/master/docs/announce/2022.03.md)

#  Additions:
 * [ ] Expose the `.file` and `.line` methods on `Label` objects -[028828ac](https://github.com/rakudo/rakudo/commit/028828ac)
 * [ ] Allow `Date` / `DateTime` *day* parameter to be a `Callable` /
      `Whatever` allowing e.g. Date.new(2022,3,*) for the last date in
      March 2022. (#4808) -[37756433](https://github.com/rakudo/rakudo/commit/37756433)
 * [ ] Make sure tools/install-dist.p6 is also available as .raku -[6ddf7529](https://github.com/rakudo/rakudo/commit/6ddf7529)
