### ISSUE TITLE
Delete TODO file

### ISSUE THREAD

**Issue by JJ** [Raku/doc#4055]
## Problem or new feature

Issues are the place to put things that need to be done. If the tasks are covered by issues, assign them to you.

## Suggestions

Delete that file, and create corresponding issues (or edit/comment existing ones)

**Comment by coke** [comment]
```
- In 101 tutorial, `(Basics)` is out of place and should not be there, but removing it we will break anchors
- In 5to6-perlfunc, the `- perlfunc` thing is ad-hoc and should not be there, but removing it will break anchors
* Operators page has broken links caused by improper formatting, should be completely re-taken.
  * It has an attempt to index concatenated `!==` operator, but it is highly insufficient and does not solve the main issue
* Pragmas page is COMPLETELY broken, every item there has wrong format, everything breaks
* Indexing of traits is just bad and inconsistent, needs a complete re-take
```

**Comment by Altai-man** [comment]
This is what gathered from the comments on https://github.com/Raku/doc/pull/4051 and merged with the TODO:

- [ ] Rename Foreign to "Other languages"
- [ ] Ignore code examples (on page like About)
- [ ] 101 tutorial has bogus anchors
- [ ] 5to6 pages are oldest and have the weirdest anchors, so needs to be re-done
- [ ] A good solution for `!==` or other concatenated operators
- [ ] Pragmas page needs a re-take
- [ ] Indexing of traits needs a meaningful system to think of and a re-take
- [ ] New Environment variables category
