### ISSUE TITLE
Checklist for 2022.06

### ISSUE THREAD

**Issue by coke** [Raku/doc#4082]
# Changes

* [x] Allow optional : on LHS of signature binding declaration [20fd4f04](https://github.com/rakudo/rakudo/commit/20fd4f04)
* [x] Make &[max] and &[min] return RHS for ties [175e716f](https://github.com/rakudo/rakudo/commit/175e716f)
* [x] Make handles on attribute of type object more natural [1c04360d](https://github.com/rakudo/rakudo/commit/1c04360d)
* [x]  Allow openbsd to locate shared libraries by version [5abd57a8](https://github.com/rakudo/rakudo/commit/5abd57a8)
* [x] Allow :from in identities [3051eefa](https://github.com/rakudo/rakudo/commit/3051eefa)
* [x] Reconsider the way $*PERL is deprecated [10d73ada](https://github.com/rakudo/rakudo/commit/10d73ada)
* [x] Allow setting ThreadPoolScheduler's max_threads to semi-infinite value [4e56f241](https://github.com/rakudo/rakudo/commit/4e56f241) | [b0ebb5e6](https://github.com/rakudo/rakudo/commit/b0ebb5e6) | [febff8fb](https://github.com/rakudo/rakudo/commit/febff8fb)

# Additions

* [x] Categorize exceptions thrown by role appliers [7a2f3b19](https://github.com/rakudo/rakudo/commit/7a2f3b19) | [9155b92b](https://github.com/rakudo/rakudo/commit/9155b92b) | [d79a261d](https://github.com/rakudo/rakudo/commit/d79a261d) | [febff8fb](https://github.com/rakudo/rakudo/commit/febff8fb)
* [x] Add :real named argument to DateTime.posix [1ffedd66](https://github.com/rakudo/rakudo/commit/1ffedd66)
* [x] Introduce (Exception|Cool).Failure coercer [51c00fdd](https://github.com/rakudo/rakudo/commit/51c00fdd)

**Comment by coke** [comment]
Everything is now checked (lizmat++), closing.
