### ISSUE TITLE
Checklist for 2022.07

### ISSUE THREAD

**Issue by dontlaugh** [Raku/doc#4104]
## Changes

- [x] Re-imagine DateTime.new(Str) / Str.DateTime  https://github.com/rakudo/rakudo/commit/aa462b41c1ef50bb75b5f137523c34fc857cc493
- [x] Make sort() a runtime error  https://github.com/rakudo/rakudo/commit/0c9169dc37f5b6efe59c8804d4461b1a4eb1ef23
- [x] Implement coercion via new-disp and re-consider return typechecking dispatcher  https://github.com/rakudo/rakudo/commit/7774c331c21fef48a7c3676f23a158d97da28f9b https://github.com/rakudo/rakudo/commit/4ab61720101007e7c262c46b249e2f1a79919d8d https://github.com/rakudo/rakudo/commit/efd610cb5422763d80e200737de9af824e7ae712 https://github.com/rakudo/rakudo/commit/b4a26fbe4a0eab79e8059ef01c50a55e849ef0e3 https://github.com/rakudo/rakudo/commit/3e45f7095a20eedf4276b102095e0eb5faa50908 https://github.com/rakudo/rakudo/commit/6c3cb8593060656c19d6ec614b0f164dde55d33f https://github.com/rakudo/rakudo/commit/f448ac47bc23a8454530175f73bb3dc3aa21922c https://github.com/rakudo/rakudo/commit/a9606b29345f237ced21d18a1cd0e80b18779cec
- [x] Make Iterable.hyper|race take Any as a default for :batch and :degree https://github.com/rakudo/rakudo/commit/d73d035e3801438b619cd8b045d377e7e999bc9f

## Additions

- [x] Implement fallback support for MRO  https://github.com/rakudo/rakudo/commit/1128d5cfee4ca963c9ab88323b6bcf7440f6d260 https://github.com/rakudo/rakudo/commit/83197e341269df720a230027ceadff4ca996131f https://github.com/rakudo/rakudo/commit/9710a85e6c091473b485aee34b5f72557a97ff73
- [x] Add IO::Path inode, dev, and devtype methods  https://github.com/rakudo/rakudo/commit/5c4970c5df4e8c63f9713c7b4d31a7b0e2d582c4 https://github.com/rakudo/rakudo/commit/599a6362befa33758167d3484175764b47580b47 https://github.com/rakudo/rakudo/commit/6dc2f92c98575b8296c8efac69b2e0166200498e
- [x] Add sub version of .head / .skip / .tail  https://github.com/rakudo/rakudo/commit/af31b1df89e0e00b80e9481062fa34bc24b3339b
- [x] Implement Haskell's "span" as "snip" in 6.e  https://github.com/rakudo/rakudo/commit/16ccb573f35d27f089a2224164098ea280a70cee

**Comment by coke** [comment]
Everything is checked, closing.
