### ISSUE TITLE
Checklist for 2022.12

### ISSUE THREAD

**Issue by coke** [Raku/doc#4154]
Improvements:

- [x] Improve flow of calling set-env.sh from a script [57337212]
- [x] Make the "needle (elem) list" message more clear [958537b1]
- [x] Make X::TypeCheck::Assignment message better [05d60e21]
- [x] Simplify X::TypeCheck::Assignment for containers [1e30b43c]

Additions:

- [x] Allow for --no-foo as alternative to --/foo when %SUB-MAIN-OPTS is set [61617b12]
- [x] Allow for -j2 as an alternative to --j=2 when %SUB-MAIN-OPTS [388924d6]
- [x] Allow for .skip(produce,skip,produce,skip,...) in 6.e [2a1ace84]
- [x] Introduce "nano" term in 6.e [10feda11][feb97323]
- [x] Add IO::Path.created returning the Instant a path was created [dbf035d8]
- [x] Introduce // as a definedness prefix operator in 6.e [d05f7eed]
- [x] Add method Any.snitch in 6.e [10066021]
- [x] Introduce Dateish.days-in-year method [3d181c89][4d43bbf9][67513cb8]
- [x] Add rotor-like capability to Str.comb in 6.e [84abeb52]
- [x] Make sure Type.are also works [983cf3ec]
- [x] Implement IO::Path.chown and chown() [1e02f566]

Placeholder for https://github.com/rakudo/rakudo/blob/master/docs/announce/2022.12.md

**Comment by coke** [comment]
See: #4153

**Comment by coke** [comment]
Everything checked, closing.
