### ISSUE TITLE
Checklist for 2023.02

### ISSUE THREAD

**Issue by coke** [Raku/doc#4209]
### Improvements:

- [x] Make use of line directive information for compile time errors [6bc209fc] [89c23ddf]
- [x] Improve error message on "foo".Order [665375ba]
- [x] Try to be more explicit when exception reporting dies [45b19784]
- [x] Make X::Method::NotFound more resilient [eff02440]

### Additions:

- [x] Allow for .rakutest as extension of Rakudo test files [4a42b211] [0d49c2e7]
- [x] Implement numeric coercers for Date/DateTime [72856df9]
- [x] Allow * to be used as identity on classify|categorize [4b264b80]
- [x] Introduce $*EXIT / $*EXCEPTION dynamic vars [50050866]
- [x] Add In Memoriam for Ben Davies [ccbf9a09][3d2f8bd9]
- [x] Add Complex.sign to v6.e [34cf82aa] (#4199)
- [x] Add Unicode class to v6.c [db7ca2dd]
- [x] Make log and sqrt handle negative values mathematically correct in v6.e [760e21c1]
- [x] Make RakuAST:: classes available with use experimental :rakuast [c9cb334e]

_note that commit IDs are for rakudo, not this repo_

**Comment by coke** [comment]
.rakutest mentioned in the intro perl6->raku section in d66241c3d, need to check remaining docs.

**Comment by lizmat** [comment]
I think the "Improvements" section can all be checked.  Or am I missing something?

**Comment by cfa** [comment]
> I think the "Improvements" section can all be checked. Or am I missing something?

Agreed; they don't seem relevant to user-facing docs.

**Comment by coke** [comment]
Everything is checked, closing.
