### ISSUE TITLE
Checklist for 2023.04

### ISSUE THREAD

**Issue by coke** [Raku/doc#4349]
# Improvements:
    - [ ] Make `Mu.WHY` a bit smarter, also handling CORE subroutines [faff9091]
    - [ ] Give `IO::Path.chown` more `unlink` like semantics [dde366ee]
    - [ ] `snip` now can also handle infinite lists [ec8cdd54]
    - [ ] Some exception message tweaking [331fd237]

# Additions:
    + use v6.e.PREVIEW or v6.* implies `use experimental :rakuast` [fcdb78ce]
    + Add rotor capabilities to sub `comb` in 6.e [28a32766]

# Fixes:
    + Fix `Range.Bool` for empty and infinite ranges in 6.e [83caae8e][188beb55]
      [53135c8d][f31a6d56]
    + Make sure `snitch` caches Seqs [61b8bee3]
    + Make prefix `//` working again [efb59f78]
    + Make `Cool.uninames` actually work [500ad5f6]
    + Make `Cool.uniname` actually match the documentation [af0c88cc]
    + Make `List.Set` work again without hanging [5a0e7a76]
    + Make `Distr.desc` correct for MacOS 11 and higher [eae02e8e]
    + Fix the git clone cmd in install docs [f79ae571]
    + Fix `IO::Path::Parts.raku` to handle type objects correctly [16924b41]
    + Fix "Unexpected named argument 'no_fallback' passed" on some meta types
      [b01d996d]
    + Warn about missing perl5 mods (Configure.pl) instead of crashing
      [6f86699f]
    + Make Supply.zip handle some potential deadlock situations better
      [6e2a46f6][2225e207]

# Removals:
    + Remove support for PERL6_EXCEPTIONS_HANDLER [5d7e3857]
