### ISSUE TITLE
Checklist for 2023.05

### ISSUE THREAD

**Issue by coke** [Raku/doc#4350]
# Improvements:

- [ ]     + Allow Nil as payload to X::AdHoc [45b3a050]
- [ ]     + Separate =input/=output from =code [6f482ca0]
- [ ]     + Handle uncontainerized type objects as invocant to AT-POS better [3139b6c0]
- [ ]     + Introduce Iterator.is-monotonically-increasing [149dd880][2edcaa35][e702f0e6]
- [ ]     + Give subsets their .^mro method [7e785883]

# Additions:

- [ ]     + Make Int.Str take a :superscript/:subscript named argument [01e82224][0248cc3e]

# Fixes:

- [ ]     + Nil.Int should coerce to 0, not to "" [70dc3c8a]
