### ISSUE TITLE
checklist for 2023.06

### ISSUE THREAD

**Issue by coke** [Raku/doc#4351]
# Improvements:

- [ ]     + Make unknown method calls on strings mention the string [563addbb]
- [ ]     + Make sure format is reported with `Formatter` errors [10cc908d]
- [ ]     + Provide better error message for `my %h = Callable` [65febb98]
- [ ]     + Make extensions for CURFS configurable [924386f5]
- [ ]     + Make `.fmt` a multi everywhere [69d570d2][a2d616a0]

# Additions:

- [ ]     + Implement `Uni.encode` [e3a74746]
- [ ]     + Add `X::Temporal::OutOfRange` [83cc6e71]
- [ ]     + Add `connect-path` and `listen-path` to IO::Socket::Async thereby implementing asynchronous Unix socket support (MoarVM only for now) [6f9bc5b1][c452fdbf]
- [ ]     + Introduce the `Format` class in 6.e [ebe0e0b2][f3bb7a2c][5a7a2e5f]
- [ ]     + Add `.fmt(Format:D)` candidates where appropriate [eceaeeae]

# Fixes:

- [ ]     + Fix role typechecking over its parent class [a4201c28]
- [ ]     + Add one more level of dirs to check for .t fudging [1dc496ad]
- [ ]     + Precomp Pipeline: Fix building on CentOS 7 [c0a95290]
- [ ]     + Consider META6.json contents when calculating CURFS id [5ec81cad]
- [ ]     + Fix copy-pasto in `Capture.Bool` [a2f71d80]

# Removals:

- [ ]     + Remove largely unknown / undocumented flags from installed raku script shims [73888f45]
