### ISSUE TITLE
checklist for 2023.08

### ISSUE THREAD

**Issue by coke** [Raku/doc#4352]
#Improvements:

- [ ]     + Re-imagine Formatter + Format updates [2cdab744][3e5a3fb6][672999fd][91f221f0][f6762fa3][6eef82f6][85c83ade][ae149fcc][64e4499a][fe788b0a][90ccaeb5][3cf10fdc][2e53c872][5deb9eed]
- [ ]     + Improve error message on iterating Ranges that can't be iterated[4562d708]
- [ ]     + Improve null regex error message a bit [19191971]
- [ ]     + Deprecate including an ambiguous .pm module file [4d5f6ff9]
- [ ]     + Don't mangle with exception backtrace (related to CompUnit) [e1b5fd0b]
- [ ]     + Respect CUPR.may-precomp() in CURI [41ae15a0]
- [ ]     + Optimize .min/.max/.minmax/.minpairs/.maxpairs [1579da00]
- [ ]     + Make reverse/unlink/rmdir complain when called w/o arguments [bfc5af69]
- [ ]     + Make X::Syntax::Confused more logical [375d04e3]

# Additions:

- [ ]     + Add sprintf(Format:D) candidate for now [120d929b]
- [ ]     + Add format.directives method [474ca30c]
- [ ]     + Add Format.AST [9ccd3c37]
- [ ]     + Add support for Version.new("1,2,3-") [73d07b4b]
- [ ]     + Make v1.2 eqv v1.2.0.0.0 True [d37e6e83]
- [ ]     + Implement methods `andthen` and `orelse` on Promise [acd8cc45]
- [ ]     + Add support for RAKUDO_NO_PRECOMPILATION environment variable [6750ab31]
- [ ]     + Implement .min|max :k :v :kv :p [ec000772]
- [ ]     + Implement .(min|max)pairs(&by) + (min|max)(&by, :foo) [4645317d]
- [ ]     + Implement List.sort(&by?, :k) to return result indices [53edf4e4] [53794833]
- [ ]     + Make sure sub versions of min/max handle adverbs [c5cc2675]
- [ ]     + Make sure sub sort takes named args and passes them on [e0a882f0]
- [ ]     + Add X::NoZeroArgMeaning exception class [fc11963d]
- [ ]     + Add sub versions of WHERE WHICH WHO (#5336) [dbde821f]
- [ ]     + Add HOW/VAR/WHAT/WHO as Mu methods [7bc98ec4]

# Fixes:

- [ ]     + Fix syntax error when building on JVM [53440ad7]
- [ ]     + Backport threadsafe update of quote-lang cache from RakuAST [60a96bb6]
- [ ]     + Fix thinko introduced in e6c0b5e919 (DateTime) [b58bf6db]
- [ ]     + Fix stringification of v6.* [8e394fad]
- [ ]     + Fix version issues when * was involved [824a500b]
- [ ]     + Make Regex.gist|raku handle absence of $!source properly [924d5341]
- [ ]     + Fix use of CALLERS/CALLER pseudo stashes [4cedc949][e334eb56][16ae94c5]
- [ ]     + Fix a coercion in `Range` constructor [b4b77952]
- [ ]     + Ensure lock is created before NativeCall role is setup [a4a2bbd2]
- [ ]     + Make $*KERNEL.bits correct on ARM64 processors [5d4bb333]
- [ ]     + Fix issue with uint64 Bufs and -1 [43473202]
- [ ]     + Fix signatures in some Code methods [866099aa]

# Removals:

- [ ]     + Remove deprecated --nqp-lib option [55537e9b]
- [ ]     + Remove deprecated Proc.status [91fdd538]
