### ISSUE TITLE
checklist for 2023.11

### ISSUE THREAD

**Issue by coke** [Raku/doc#4453]
New in 2023.11:

+ Improvements:
    * [ ] Don't open handles when calling Distribution.content [9db25993]
    * [ ] Use new stat-time-nanos syscall (in IO::Path) [cc15340f]

+ Additions:
    * [ ] Add :slang argument to Cool.AST [4707dc5a]
    * [ ] Add L10N::PT [d1812ff1]
    * [ ] Add "Sonoma" as known MacOS description (for v14 in Distro) [08b35312]
    * [ ] Add Raku.legacy implementation-detail class method [a9da976e]

+ Fixes:
    * [ ] Check if requested backtrace is null (fixes jvm bug) [76bfebf5]
    * [ ] (Re-)align backtraces on JVM with MoarVM [53a79941]
    * [ ] Fix handling of dynamic containers on 6.e PseudoStash [0479e2fd]
    * [ ] Make sure that "no actions" really means it (in grammars) [bd2c719e]
    * [ ] Replace incorrect CoC report link [2846ea59]
    * [ ] Fix some aspects of using "is default" [8b800e02][c0b19bec][4b7a9bf6]
      [d32b729a][c34d60b6]
    * [ ] Fix X::Hash::Store::OddNumber message with undefined last element [f29cecfa]
    * [ ] Fix a regression where exception is thrown for a generic type [49ddf5fe]

+ Removals:
    * [ ] Remove largely unknown flags from installed raku script shims [bdd77290]
