### ISSUE TITLE
Checklist for 2023.12

### ISSUE THREAD

**Issue by coke** [Raku/doc#4454]
New in 2023.12:

+ Improvements:
    * [ ] Don't set callers $/ with Grammar.parse in 6.e [8542ad21]
    * [ ] Move close to complete generic instantiation [fc2a5f64][97e6a436]
      [7739c0d0][aa83d509][2df1be5d][4076476f][eabc07c3][d8a063ae][056f9c33]
      [3d05492c][b4fd57bf][0b544d6d][5190dcc6][9614026d][5f9f094a][63f24857]
      [2e453b9c][eef5734b][aa8fbd5b][4218796a][f8a17994][67194314][f4cad695]
      [b9c09832][21d35888][44f529da][fcd787c1][7e73023b][510c3156][c22439e5]
      [5f8cf56f][fe40b8e8][09429104][c6890b40][c032e2f8][18d626bd][3c88689b]
      [c6f4a09c][6c0b54e5][15a787cb][4d38d698][69dd7d66][52aec48c]

+ Additions:
    * [ ] Make the Format class a Callable [bd43800b]

+ Fixes:
    * [ ] Fix rare deadlocks during supply setup [d31e4f62][6fe16327]
    * [ ] Make sure :chomp is honoured on $*ARGFILES.lines [8dca71e8]
    * [ ] Make sure if 1..0 { } does NOT fire in 6.e [4e75ae14]
    * [ ] Make Match.print more aware of its surroundings [5606fb65]
