### ISSUE TITLE
checklist for 2024.02

### ISSUE THREAD

**Issue by coke** [Raku/doc#4456]
+ Improvements:
    * [ ] Better errors for common array parameter mistakes [47fb8c35]
    * [ ] Improve stability in heavy async situations [761153bc][5c289878]

+ Additions:
    * [ ] Add Int/Real coercing versions of `infix:<div|mod>` [71c0151a]
    * [ ] Implement sub form of &trans, mainly to support feed operators [b238fad8]
    * [ ] Provide native int coercers to Int/Cool [a67842ac][1eaa9d71][dc5414d6]

+ Fixes:
    * [ ] Avoid leaking repo.lock handle [155818f4][e6207699][7ca96bbd][a723c387]
