### ISSUE TITLE
checklist for 2024.04

### ISSUE THREAD

**Issue by coke** [Raku/doc#4458]
+ Improvements:
    * [ ] Make X::Syntax::Number::LiteralType a subclass of
      X::TypeCheck::Assignment [5b7cf94c]
    * [ ]  Make Rakudo up to 2x as fast on the JVM backend by using fastutil [05aae712][23a9fdbe]
      [955bc856]

+ Additions:
    * [ ]  Add Allomorph.narrow [e6a28e1c]
    * [ ]  Add dispatch disambiguation via 'is item' parameter trait [70f16f63]
      [3b42de18][36901bb0][0ce55752][c02bd131]
