### ISSUE TITLE
checklist for 2024.05

### ISSUE THREAD

**Issue by coke** [Raku/doc#4479]
# Improvements:

* [ ] Provide the host:port that compose the address in use [ecd2dd46]
* [ ] Improve .IO.open.lock failure messages [774cc864]
* [ ] Make (^Inf).reverse fail rather than infiniloop [26f1c494]
* [ ]  Provide deeper context into `run` failures [aca5e4c1]

+ Additions:
* [ ] Add rakudo flavor [6e55b118][c888a116][f253d68b][69a33564]
* [ ] Add worry for WhateverCode on LHS of smartmatch [d9863e9a]
* [ ] Add Cool.nomark in 6.e [5eb1da8c]
* [ ] Introduce Any.are(type --> Bool:D) in 6.e [23b94de6]
* [ ] Add :invocant option to Parameter.new [f17cd58f]
